version: "3.7"

services:
  master:
    build:
      context: .
      dockerfile: ./master/Dockerfile
    ports:
      - "9870:9870"
      - "8088:8088"
      - "19888:19888"
    container_name: master
    volumes: 
      - ./data:/data_volume
  worker-1:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    container_name: worker-1
  worker-2:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    container_name: worker-2